- src/router/service.js
- src/views/service/LoginView.vue
> title : [feat] 로그인 페이지 구현

- src/views/service/SignupView.vue
> title : [feat] 회원가입 페이지 프레임 구현 [#10]

- src/router/service.js
- src/views/service/EmailAuthenticationView.vue
> title : [feat] 이메일 인증 페이지를 구현한다.

- src/components/Form/CompleteForm.vue
- src/router/service.js
- src/views/service/PurchaseView.vue
- src/views/service/purchase/BasicInfoView.vue
- src/views/service/purchase/CarTypeView.vue
- src/views/service/purchase/ChoiceCarView.vue
- src/views/service/purchase/ContractView.vue
- src/views/service/purchase/DeliveryView.vue
- src/views/service/purchase/DoneView.vue
- src/views/service/purchase/InsurancesView.vue
- src/views/service/purchase/LoansView.vue
- src/views/service/purchase/SearchCarView.vue
> [feat] 일반 구매 로직 추가

- src/layouts/service/myPage/Default.vue
- src/views/service/mypage/MemberInfoView.vue
- 패스워드 수정 시 패스워드 확인과 일치 여부 확인
- #5
> [refactor]/회원 상세페이지 수정

- src/components/FindAddress.vue
- src/components/HomeMain.vue
- src/components/card/Card.vue
- src/components/card/CardBtn.vue
- src/components/common/ImageAttach.vue
- src/store/btnStore.js
- src/store/retrieveCar/retrieveCar.js
- src/store/sales/saleStore.js
- src/store/sales/saleValidateStore.js
- src/views/service/sales/CarInfo.vue
- src/views/service/sales/CarRetrieve.vue
- src/views/service/sales/ContractView.vue
- src/views/service/sales/DoneView.vue
- src/views/service/sales/ImageInput.vue
- src/views/service/sales/MeetingLocation.vue
- src/views/service/sales/PriceAndAccount.vue
- 폼 유효성 검사 (button disable)
- 뒤로가기 했을 때 폼 유지
- #3
> [refactor] 판매 폼 유효성 검사

- src/components/Form/BasicForm.vue
- src/components/Form/CarTypeForm.vue
- src/components/Form/ChoiceCarForm.vue
- src/components/Form/ScrollComponent.vue
- src/components/products/details/BasicCarInfo.vue
- src/components/products/details/CarDiagnosis.vue
- src/components/products/details/FinancialService.vue
- src/components/products/details/ImageSlider.vue
- src/components/products/details/MileageAnalysis.vue
- src/components/service/Dialog.vue
- src/layouts/service/myPage/Default.vue
- src/views/service/SignupConsentView.vue
- src/views/service/mypage/MemberInfoView.vue
- src/views/service/mypage/PurchaseHistoryDetailView.vue
- src/views/service/mypage/PurchaseHistoryView.vue
- src/views/service/mypage/SaleHistoryDetailView.vue
- src/views/service/mypage/SaleHistoryView.vue
- src/views/service/products/ProductDetails.vue
> [style] 전반적인 UI 스타일 변경

- src/apis/admin/logss/logAPI.js
- src/apis/admin/member/memberAPI.js
- src/views/admin/logs/LogManagementView.vue
- src/views/admin/members/MemberManagementView.vue
> [feat] admin 페이지 구현

- src/components/Form/ChoiceCarForm.vue
- src/components/Form/FinanceForm.vue
- src/components/Form/SearchCarForm.vue
- src/components/service/Dialog.vue
> [feat] 일반구매 연결

- src/layouts/admin/default/TheSidebar.vue
> [fix] npm run build 오류 해결

- src/components/products/details/CarDiagnosis.vue
- src/views/service/mypage/MemberInfoView.vue
> [fix] merge 후 issue 해결

- src/components/common/ImageAttach.vue
- src/components/products/details/CarDiagnosis.vue
- src/layouts/admin/default/TheSidebar.vue
- src/views/admin/members/MemberManagementView.vue
> [refactor] 관리자 페이지 검색바 제거

- src/store/contractStore.js
- src/views/service/OneClickSaleView.vue
- src/views/service/PurchaseView.vue
- src/views/service/SignupConsentView.vue
- src/views/service/SignupView.vue
> [feat] 회원가입 문서 동의 항목 연동

- src/components/common/ImageAttach.vue
- src/views/service/OneClickSaleView.vue
- src/views/service/sales/ContractView.vue
- src/views/service/sales/PriceAndAccountView.vue
> [hotfix] 뒤로가기 시 가격 오류 수정

- src/apis/admin/products/productAPI.js
- src/components/admin/products/UpdateCarInfo.vue
- src/components/common/BtnBlack.vue
> [fix] 버튼 눌렀을 시 발생하는 오류 해결

- src/components/Form/ChoiceCarForm.vue
- src/components/card/Card.vue
- src/components/card/CardBtn.vue
- src/store/purchase/purchaseStore.js
- src/store/sales/saleStore.js
- src/views/service/OneClickPurchaseView.vue
- src/views/service/OneClickSaleView.vue
- src/views/service/PurchaseView.vue
- src/views/service/common/DoneView.vue
- src/views/service/mypage/SaleHistoryView.vue
- src/views/service/purchase/ContractView.vue
- src/views/service/sales/ContractView.vue
- src/views/service/sales/MeetingView.vue
- router 마이페이지로 이동
- #3
- 상세로는 못가고.. 목록으로 갑니데이..
> [refactor] router 마이페이지로 이동

- src/apis/service/contracts/contractApi.js
- src/apis/service/histories/sales/saleApi.js
- src/components/card/CardBtn.vue
- src/components/common/BtnBlack.vue
- src/store/auth.js
- src/store/btnStore.js
- src/store/sales/saleStore.js
- src/views/service/OneClickSaleView.vue
- src/views/service/SignupConsentView.vue
- src/views/service/mypage/PurchaseHistoryView.vue
- src/views/service/purchase/BasicInfoView.vue
- src/views/service/purchase/DoneView.vue
- src/views/service/sales/BasicInfo.vue
- src/views/service/sales/CarInfo.vue
- src/views/service/sales/CarRetrieve.vue
- src/views/service/sales/DoneView.vue
- src/views/service/sales/ImageInput.vue
- src/views/service/sales/MeetingLocation.vue
- src/views/service/sales/OneClickSaleView.vue
- src/views/service/sales/PriceAndAccount.vue
> [Release] Sprint-5-2 to develop

- src/components/products/details/BasicCarInfo.vue
- src/layouts/service/myPage/Default.vue
- src/layouts/service/myPage/View.vue
- src/router/index.js
- src/router/service.js
- src/store/route.js
- src/views/service/SignupConsentView.vue
- src/views/service/SignupView.vue
- src/views/service/mypage/MemberInfoView.vue
> [Refactor] 마이페이지 및 기타 등등

- src/apis/admin/products/productAPI.js
- src/views/admin/products/ProductDetailView.vue
> fix : 관리자 페이지 조회 수정

- src/apis/admin/logss/logAPI.js
- src/apis/admin/member/memberAPI.js
- src/router/admin.js
- src/router/index.js
- src/router/service.js
- src/store/auth.js
> [hotfix] admin router 처리
